---
- name: Detects if running inside container
  ansible.builtin.set_fact:
    docker_host_is_container: "{{ (ansible_facts.virtualization_role == 'guest') and
      (ansible_facts.virtualization_type in ['docker', 'podman', 'lxc', 'openvz']) }}"

- name: Include OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts.os_family | lower }}.yml"

- name: Install Docker and Docker Compose
  ansible.builtin.package:
    name: "{{ docker_install_pkgs }}"
    state: present
  become: true

- name: Post-install tasks - Rootful mode
  ansible.builtin.include_tasks:
    file: postinstall_rootful.yml
  when: docker_enable_rootless_mode is not truthy

- name: Post-install tasks - Rootless mode
  ansible.builtin.include_tasks:
    file: postinstall_rootless.yml
  when: docker_enable_rootless_mode is truthy

- name: Create docker daemon directory
  ansible.builtin.file:
    path: "{{ docker_daemon_json_path | dirname }}"
    mode: "0755"
    state: directory

- name: Configure docker daemon
  ansible.builtin.copy:
    content: "{{ docker_daemon_json_content | from_json | to_nice_json }}"
    dest: "{{ docker_daemon_json_path }}"
    mode: "0644"
    backup: true
    validate: dockerd --config-file=%s --validate
  diff: true
  become: "{{ not docker_enable_rootless_mode }}"
  notify: Restart docker daemon

- name: Apply notified handlers
  ansible.builtin.meta: flush_handlers

- name: Check if daemon is rootless
  ansible.builtin.command:
    argv:
      - docker
      - info
      - --format
      - >-
        {% raw %}{{ range .SecurityOptions }}{{ if eq . "name=rootless" }}true{{ end }}{{ end }}{% endraw %}
  changed_when: false
  register: docker_daemon_check_rootless
  failed_when: docker_daemon_check_rootless.stdout != 'true'
  when: docker_enable_rootless_mode is truthy

- name: Validate install
  ansible.builtin.command:
    cmd: docker run --rm hello-world
  changed_when: false
  # Doesn't work in containers
  when: not docker_host_is_container
