---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: docker
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: /sbin/init
    stop_signal: SIGRTMIN+3
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    tmpfs: [/run, /run/lock, /tmp]
    cgroupns_mode: host
    # Necessary for dockerd to start ("mount" operations)
    privileged: true
    # pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: ansible
      # # Avoids "sudo" problem in rl9
      # remote_user: root
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
